apiVersion: backstage.io/v1alpha1
kind: infra-service/construct
metadata:
  name: private-dns-zone
  description: Repository for construct
  annotations:
    backstage.io/managed-by-location: >-
      url:https://contregietbmrpet01.azurecr.io/bicep/constructs/private-dns-zone
    backstage.io/managed-by-origin-location: >-
      url:https://contregietbmrpet01.azurecr.io/bicep/constructs/private-dns-zone
  tags:
    - construct
    - container
    - azure
spec:
  type: construct
  lifecycle: production
  owner: team-name
  links:
    - url: https://contregietbmrpet01.azurecr.io/bicep/constructs/private-dns-zone
      title: Container Registry
      icon: link
  version: 0.2.2
  manifests:
    - digest: sha256:de524c67038f1224062f109200e40b61097454c3ad2906d9cdfd8689ba94922c
      tags:
        - 0.2.1
      createdOn: 2023-06-30T12:01:15.345Z
      lastUpdatedOn: 2023-06-30T12:01:15.345Z
    - digest: sha256:fcbd977f38cd27ee643ef5c6fc9031a644465d436cf9325a4c95b6d3c7aff0c2
      tags:
        - 0.2.2
      createdOn: 2024-03-11T15:02:23.816Z
      lastUpdatedOn: 2024-03-11T15:02:23.816Z
