apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: Repository for constructs
  annotations:
    backstage.io/managed-by-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/grafana
    backstage.io/managed-by-origin-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/grafana
    backstage.io/techdocs-ref: >-
      url:https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/grafana/README.md
  tags:
    - constructs
    - container
    - azure
spec:
  type: constructs
  lifecycle: production
  owner: team-name
  links:
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/grafana/main.bicep
      title: Source Code
      icon: link
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/grafana/README.md
      title: Readme
      icon: link
  version: 0.1.3
  manifests:
    - tags:
        - 0.1.2
      createdOn: 2025-01-24T05:03:41.134Z
      lastUpdatedOn: 2025-01-24T05:03:41.134Z
    - tags:
        - 0.1.3
      createdOn: 2025-02-27T17:22:48.886Z
      lastUpdatedOn: 2025-02-27T17:22:48.886Z
    - tags:
        - 0.1.1
      createdOn: 2024-10-30T13:22:25.539Z
      lastUpdatedOn: 2024-10-30T13:22:25.539Z
