apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iot-dps
  description: Repository for constructs
  annotations:
    backstage.io/managed-by-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/iot-dps
    backstage.io/managed-by-origin-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/iot-dps
  tags:
    - constructs
    - container
    - azure
spec:
  type: constructs
  lifecycle: production
  owner: team-name
  links:
    - url: https://contregietbmrpet01.azurecr.io/bicep/constructs/iot-dps
      title: Container Registry
      icon: link
  version: 0.1.2
  manifests:
    - digest: sha256:2de4f5e2c2f1740d254a183a94b5b69b0864dfa8a9cdbb515eb72e7b0fda8ac3
      tags:
        - 0.1.1
      createdOn: 2023-09-29T05:17:54.219Z
      lastUpdatedOn: 2023-09-29T05:17:54.219Z
    - digest: sha256:779c6de5055f6fa2f9144686f33b5b070286a2a8b8a6d0fcaaecef06bc50326a
      tags:
        - 0.1.2
      createdOn: 2024-03-08T10:37:39.310Z
      lastUpdatedOn: 2024-03-08T10:37:39.310Z
