apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: key-vault
  description: Repository for constructs
  annotations:
    backstage.io/managed-by-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/key-vault
    backstage.io/managed-by-origin-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/key-vault
    backstage.io/techdocs-ref: >-
      url:https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/key-vault/README.md
  tags:
    - constructs
    - container
    - azure
spec:
  type: constructs
  lifecycle: production
  owner: team-name
  links:
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/key-vault/main.bicep
      title: Source Code
      icon: link
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/key-vault/README.md
      title: Readme
      icon: link
  version: 0.2.3
  manifests:
    - tags:
        - 0.1.1
      createdOn: 2023-06-13T21:53:15.480Z
      lastUpdatedOn: 2023-06-13T21:53:15.480Z
    - tags:
        - 0.2.2
      createdOn: 2024-03-06T10:27:00.631Z
      lastUpdatedOn: 2024-03-06T10:27:00.631Z
    - tags:
        - 0.2.3
      createdOn: 2024-03-11T15:24:08.088Z
      lastUpdatedOn: 2024-03-11T15:24:08.088Z
    - tags:
        - 0.2.1
      createdOn: 2023-06-28T12:58:36.073Z
      lastUpdatedOn: 2023-06-28T12:58:36.073Z
