apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linux-vm
  description: Repository for constructs
  annotations:
    backstage.io/managed-by-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/linux-vm
    backstage.io/managed-by-origin-location: url:https://contregietbmrpet01.azurecr.io/bicep/constructs/linux-vm
    backstage.io/techdocs-ref: >-
      url:https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/linux-vm
  tags:
    - constructs
    - container
    - azure
spec:
  type: constructs
  lifecycle: production
  owner: team-name
  links:
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/linux-vm/main.bicep
      title: Source Code
      icon: link
    - url: >-
        https://github.com/bh-ent-tech/bh-bicep-registry-modules/blob/main/modules/constructs/linux-vm/README.md
      title: Readme
      icon: link
  version: 0.1.1
  manifests:
    - tags:
        - 0.1.1
      createdOn: 2023-06-28T17:24:12.071Z
      lastUpdatedOn: 2023-06-28T17:24:12.071Z
