apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: Helm chart for pgadmin
  name: pgadmin
spec:
  appVersion: 1.16.0
  chartVersion: 0.1.4
  lifecycle: production
  owner: platform-team
  type: service
